# Generated by Django 4.2.5 on 2023-09-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre usuario')),
                ('password', models.CharField(max_length=100, verbose_name='<PASSWORD>')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
