# Generated by Django 4.2.5 on 2023-09-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='root',
            name='username',
        ),
        migrations.AddField(
            model_name='root',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre(s)'),
        ),
        migrations.AddField(
            model_name='root',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Apellido(s)'),
        ),
        migrations.AddField(
            model_name='root',
            name='rol',
            field=models.CharField(default='root', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='root',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
