# Generated by Django 4.2.5 on 2023-10-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_root_username_root_first_name_root_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='root',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='root',
            name='last_name',
        ),
        migrations.AddField(
            model_name='root',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='root',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Password'),
        ),
    ]
