# Generated by Django 4.2.5 on 2023-10-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_root_first_name_remove_root_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='root',
            name='rol',
        ),
    ]
